import type { Metadata } from "next";
import "./globals.css"; // ✅ Make sure the path is correct (relative to this file)
import { AuthProvider } from "@/contexts/AuthContext";
import AuthGate from "@/components/AuthGate";
export const metadata: Metadata = {
  title: "SQL Polling App",
  description: "Generated by SQL Polling App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="true">
        <AuthProvider>
          {/* <AuthGate> */}
          {children}
          {/* </AuthGate> */}
        </AuthProvider>
      </body>
    </html>
  );
}
